"""Rootly environment variable names and defaults."""

from __future__ import annotations

ROOTLY_API_TOKEN_ENV = "ROOTLY_API_TOKEN"
ROOTLY_BASE_URL_ENV = "ROOTLY_BASE_URL"
ROOTLY_TIMEOUT_SECONDS_ENV = "ROOTLY_TIMEOUT_SECONDS"

DEFAULT_ROOTLY_TIMEOUT_SECONDS = 15.0

__all__ = [
    "DEFAULT_ROOTLY_TIMEOUT_SECONDS",
    "ROOTLY_API_TOKEN_ENV",
    "ROOTLY_BASE_URL_ENV",
    "ROOTLY_TIMEOUT_SECONDS_ENV",
]
