"""Synthesize the kubeconfig ``gcloud container clusters get-credentials`` writes.

The generated document holds **no secret**. A GKE kubeconfig is three public
facts — the API server endpoint, the cluster's CA certificate, and the name of
a binary — plus an ``exec`` directive telling the Kubernetes client to ask
``gke-gcloud-auth-plugin`` for a token at connection time. That property is the
reason auto-registration is safe to do unattended: nothing durable is written
that would be worth stealing.

The identity the plugin presents is *not* automatically the identity OpenSRE
used to discover the cluster. Left to its own devices the plugin shells out to
``gcloud config config-helper``, so it is whoever ran ``gcloud auth login`` —
and where gcloud is absent, as in the container image, it is nobody: the plugin
exits non-zero, the Kubernetes client falls back to an unauthenticated request,
and the API server answers ``system:anonymous ... Forbidden``.

:func:`build_kubeconfig` therefore always passes
``--use_application_default_credentials``, which is the same credential chain
``integrations.gcp.client.resolve_credentials`` uses, and mirrors the rest of
that chain into the exec block: a service-account key *file* is pinned via
``GOOGLE_APPLICATION_CREDENTIALS``, and impersonation is forwarded as
``--impersonate_service_account``. Discovery and connection then present one
identity. This adds no new requirement — the GCP tools already resolve ADC, so
a setup without it cannot discover a cluster to register in the first place. An
inline JSON key cannot be pinned this way — see :func:`credentials_path_for`.
"""

from __future__ import annotations

import shutil
from typing import Any

import yaml

#: The binary the generated kubeconfig delegates authentication to. Ships with
#: the gcloud SDK as a separate component, so being on PATH is not implied by
#: gcloud itself being installed.
AUTH_PLUGIN = "gke-gcloud-auth-plugin"

#: Exec credential plugin contract version. ``v1beta1`` is what current gcloud
#: emits and what the Python Kubernetes client's exec provider speaks.
_EXEC_API_VERSION = "client.authentication.k8s.io/v1beta1"

_INSTALL_HINT = (
    "Install with: gcloud components install gke-gcloud-auth-plugin "
    "(or apt/yum install google-cloud-cli-gke-gcloud-auth-plugin)."
)

#: Environment variable the plugin reads to locate a service-account key.
_ADC_ENV = "GOOGLE_APPLICATION_CREDENTIALS"

#: Makes the plugin resolve Application Default Credentials itself. Without it
#: the plugin shells out to ``gcloud``, which is not installed in the container
#: image and is the wrong identity on a workstation.
_ADC_FLAG = "--use_application_default_credentials"

#: Layers impersonation on the ambient credential, as ``resolve_credentials``
#: does for the API clients.
_IMPERSONATE_FLAG = "--impersonate_service_account"


def plugin_installed() -> bool:
    """Return whether :data:`AUTH_PLUGIN` is on ``PATH``."""
    return shutil.which(AUTH_PLUGIN) is not None


def credentials_path_for(service_account_key: str) -> str:
    """Return the key *file path* to pin the plugin to, or ``""``.

    The GCP integration accepts a service-account key as either a path or
    literal JSON. Only the path form can be handed to the plugin — pinning the
    inline form would mean writing the key to disk, which trades a
    secret-free kubeconfig for a secret on the filesystem. Callers warn instead.
    """
    text = (service_account_key or "").strip()
    return "" if not text or text.startswith("{") else text


def build_kubeconfig(
    *,
    context: str,
    endpoint: str,
    ca_certificate: str,
    credentials_path: str = "",
    impersonate_service_account: str = "",
) -> str:
    """Render a single-cluster kubeconfig as YAML.

    ``context`` names the cluster, context and user alike, matching gcloud so a
    kubeconfig generated here and one generated by gcloud are interchangeable —
    which is what lets the correlation in ``gcp_list_gke_clusters`` recognise
    either. ``ca_certificate`` is passed through as-is: ``container/v1`` already
    returns it base64-encoded, which is exactly what
    ``certificate-authority-data`` expects.

    ``credentials_path`` and ``impersonate_service_account`` carry the GCP
    integration's own credential settings into the exec block so the plugin
    authenticates as the identity that discovered the cluster; see the module
    docstring.
    """
    args = [_ADC_FLAG]
    if impersonate_service_account:
        args.append(f"{_IMPERSONATE_FLAG}={impersonate_service_account}")

    exec_block: dict[str, Any] = {
        "apiVersion": _EXEC_API_VERSION,
        "command": AUTH_PLUGIN,
        "args": args,
        "installHint": _INSTALL_HINT,
        "provideClusterInfo": True,
    }
    if credentials_path:
        exec_block["env"] = [{"name": _ADC_ENV, "value": credentials_path}]

    document = {
        "apiVersion": "v1",
        "kind": "Config",
        "clusters": [
            {
                "name": context,
                "cluster": {
                    "server": f"https://{endpoint}",
                    "certificate-authority-data": ca_certificate,
                },
            }
        ],
        "contexts": [
            {
                "name": context,
                "context": {"cluster": context, "user": context},
            }
        ],
        "current-context": context,
        "users": [{"name": context, "user": {"exec": exec_block}}],
    }
    return yaml.safe_dump(document, sort_keys=False)
