"""Synthesize the kubeconfig ``gcloud container clusters get-credentials`` writes.

The generated document holds **no secret**. A GKE kubeconfig is three public
facts — the API server endpoint, the cluster's CA certificate, and the name of
a binary — plus an ``exec`` directive telling the Kubernetes client to ask
``gke-gcloud-auth-plugin`` for a token at connection time. That property is the
reason auto-registration is safe to do unattended: nothing durable is written
that would be worth stealing.

The identity the plugin presents is *not* automatically the identity OpenSRE
used to discover the cluster. The plugin resolves Application Default
Credentials on its own, so on a workstation it is whoever ran ``gcloud auth
login``. When the GCP integration is configured with a service-account key
*file*, :func:`build_kubeconfig` pins the plugin to that same file via
``GOOGLE_APPLICATION_CREDENTIALS`` in the exec ``env`` block, so discovery and
connection agree. An inline JSON key cannot be pinned this way — see
:func:`credentials_path_for`.
"""

from __future__ import annotations

import shutil
from typing import Any

import yaml

#: The binary the generated kubeconfig delegates authentication to. Ships with
#: the gcloud SDK as a separate component, so being on PATH is not implied by
#: gcloud itself being installed.
AUTH_PLUGIN = "gke-gcloud-auth-plugin"

#: Exec credential plugin contract version. ``v1beta1`` is what current gcloud
#: emits and what the Python Kubernetes client's exec provider speaks.
_EXEC_API_VERSION = "client.authentication.k8s.io/v1beta1"

_INSTALL_HINT = (
    "Install with: gcloud components install gke-gcloud-auth-plugin "
    "(or apt/yum install google-cloud-cli-gke-gcloud-auth-plugin)."
)

#: Environment variable the plugin reads to locate a service-account key.
_ADC_ENV = "GOOGLE_APPLICATION_CREDENTIALS"


def plugin_installed() -> bool:
    """Return whether :data:`AUTH_PLUGIN` is on ``PATH``."""
    return shutil.which(AUTH_PLUGIN) is not None


def credentials_path_for(service_account_key: str) -> str:
    """Return the key *file path* to pin the plugin to, or ``""``.

    The GCP integration accepts a service-account key as either a path or
    literal JSON. Only the path form can be handed to the plugin — pinning the
    inline form would mean writing the key to disk, which trades a
    secret-free kubeconfig for a secret on the filesystem. Callers warn instead.
    """
    text = (service_account_key or "").strip()
    return "" if not text or text.startswith("{") else text


def build_kubeconfig(
    *,
    context: str,
    endpoint: str,
    ca_certificate: str,
    credentials_path: str = "",
) -> str:
    """Render a single-cluster kubeconfig as YAML.

    ``context`` names the cluster, context and user alike, matching gcloud so a
    kubeconfig generated here and one generated by gcloud are interchangeable —
    which is what lets the correlation in ``gcp_list_gke_clusters`` recognise
    either. ``ca_certificate`` is passed through as-is: ``container/v1`` already
    returns it base64-encoded, which is exactly what
    ``certificate-authority-data`` expects.
    """
    exec_block: dict[str, Any] = {
        "apiVersion": _EXEC_API_VERSION,
        "command": AUTH_PLUGIN,
        "installHint": _INSTALL_HINT,
        "provideClusterInfo": True,
    }
    if credentials_path:
        exec_block["env"] = [{"name": _ADC_ENV, "value": credentials_path}]

    document = {
        "apiVersion": "v1",
        "kind": "Config",
        "clusters": [
            {
                "name": context,
                "cluster": {
                    "server": f"https://{endpoint}",
                    "certificate-authority-data": ca_certificate,
                },
            }
        ],
        "contexts": [
            {
                "name": context,
                "context": {"cluster": context, "user": context},
            }
        ],
        "current-context": context,
        "users": [{"name": context, "user": {"exec": exec_block}}],
    }
    return yaml.safe_dump(document, sort_keys=False)
